name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout libcups
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2.0.0
    - name: Install Prerequisites
      run: cd vcnet; nuget restore libcups.sln; cd ../pdfio; nuget restore
    - name: Build libcups
      run: cd vcnet; msbuild libcups.sln
      
    - name: tar
      run: |
         mkdir ipptool
         copy packages\libressl_native.redist.3.7.3\build\native\bin\x64\Debug\ssl.dll ipptool
         copy packages\libressl_native.redist.3.7.3\build\native\bin\x64\Debug\crypto.dll ipptool
         copy x64\Debug\*.dll ipptool
         tar cvf ipptool.zip ipptool

    - name: upload release
      uses: softprops/action-gh-release@v2
      with:
        files: |
            ipptool.zip
        draft: false
        prerelease: false
        tag_name: ${{ github.ref_name }}
